site_name: NFDIcore Ontology
theme: readthedocs
#theme: mkdocs
nav:
  - Welcome: welcome.md
  - Introduction: intro.md
  - Versions: versions.md
  - Ontology: ontology.md
  - Competency Questions: questions.md
  - Contributing: contributing.md


