site_name: NFDIcore Ontology
theme: readthedocs
#theme: mkdocs
nav:
  - Welcome: index.md
  - Introduction: intro.md
  - Ontology: ontology.md
  - Patterns: patterns.md
  - Versions: versions.md
  - Modular Extensions: extensions.md 
  #- Competency Questions: questions.md
  - Contributing: contributing.md


