site_name: NFDIcore Ontology
theme: readthedocs
#theme: mkdocs
nav:
  - Welcome: index.md
  - Introduction: intro.md
  - Ontology: ontology.md
  - Patterns: patterns.md
  - Versions: versions.md
  - Modular Extensions: extensions.md 
  #- Competency Questions: questions.md
  - Contributing: contributing.md
  - Contact: contact.md



markdown_extensions:
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        # Mermaid diagrams
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
#  - optionalConfig.js
  - https://cdn.jsdelivr.net/npm/mermaid@11.12.0/dist/mermaid.min.js
  - extra-loader.js