PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
# every nfdi class needs a label
SELECT ?a WHERE {
    ?a rdf:type owl:Class .
    FILTER REGEX (str(?a), "nfdi", "i") .
    OPTIONAL {
       ?a rdfs:label ?l .
    }
   FILTER (!BOUND(?l))
}

