name: Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - odk

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
          echo ${REPO}
          echo ${GITHUB_REPOSITORY}
      - name: Build and Push
        env:
          REGISTRY: ghcr.io
        run: |
          docker build -t $REGISTRY/${REPO}:latest -t $REGISTRY/${REPO}:$(date +%s) .  
          docker push $REGISTRY/${REPO} --all-tags
