name: reasoning example
on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: main
        path: main
    - name: Reasoning example
      run: |
           ls -la           
           curl -L -o robot.jar "https://github.com/ontodev/robot/releases/latest/download/robot.jar"
           java -jar robot.jar --version
           java -jar robot validate-profile --profile DL --input main/nfdicore.ttl --output validation.txt
           cat validation.txt
