name: Update the /docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - nfdicore.ttl

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - uses: actions/cache@v2
        name: Configure pip caching
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-publish-pip-${{ hashFiles('**/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-publish-pip-
      - name: Install dependencies
        run: |
          pip install pyLODE==3.0.1 httpx==0.21.1
      - name: Generate LODE docs
        run: |-
          python docs/update.py nfdicore.ttl
        env:
          SCHPIEL_TOKEN: ${{ secrets.SCHPIEL_TOKEN }}
          DOCS_URI: ${{secrets.DOCS_URI}}
