name: HTML

on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: main
        path: main
    - name: Build HTML for main
      run: |
           wget -O widoco.jar https://github.com/dgarijo/Widoco/releases/download/v1.4.25/widoco-1.4.25-jar-with-dependencies_JDK-11.jar
           mkdir public
           java -jar widoco.jar -ontFile main/nfdicore.ttl -outFolder public -uniteSections -includeAnnotationProperties -lang en-de  -getOntologyMetadata -noPlaceHolderText -rewriteAll -webVowl
           ls public
           echo -e "\n img { max-width:1000px }" >> public/doc/resources/extra.css
           cat public/doc/resources/extra.css
           mv public/doc/* public/
           cp public/index-en.html public/index.html
           cp -r public 3.0.0
           mv 3.0.0 public/


           pip install mkdocs
           cd main
           mkdocs build -f mkdocs.yaml

           cd ..
           mkdir public/docs
           cp -r main/site/* public/docs/

    - uses: actions/checkout@v3
      with:
        ref: v2.1.0
        path: v2.1.0
    - name: Build HTML for 2.1.0
      run: |
           mkdir public/2.1.0 
           java -jar widoco.jar -ontFile v2.1.0/nfdicore.ttl -outFolder public/2.1.0  -uniteSections -includeAnnotationProperties -lang en-de  -getOntologyMetadata -noPlaceHolderText -rewriteAll -webVowl
           ls public/2.1.0/
           mv public/2.1.0/doc/* public/2.1.0/
           cp public/2.1.0/index-en.html public/2.1.0/index.html



    - uses: actions/checkout@v3
      with:
        ref: v2.0.0
        path: v2.0.0
    - name: Build HTML for 2.0.0
      run: |
           mkdir public/2.0.0 
           java -jar widoco.jar -ontFile v2.0.0/nfdicore.ttl -outFolder public/2.0.0  -uniteSections -includeAnnotationProperties -lang en-de  -getOntologyMetadata -noPlaceHolderText -rewriteAll -webVowl
           ls public/2.0.0/
           mv public/2.0.0/doc/* public/2.0.0/
           cp public/2.0.0/index-en.html public/2.0.0/index.html

    - uses: actions/checkout@v3
      with:
        ref: v1.1.1
        path: v1.1.1
    - name: Build HTML for 1.1.1
      run: |
           mkdir public/1.1.1 
           java -jar widoco.jar -ontFile v1.1.1/nfdicore.ttl -outFolder public/1.1.1  -uniteSections -includeAnnotationProperties -lang en-de  -getOntologyMetadata -noPlaceHolderText -rewriteAll -webVowl
           ls public/1.1.1/
           mv public/1.1.1/doc/* public/1.1.1/
           cp public/1.1.1/index-en.html public/1.1.1/index.html
    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v3
      with:
        target_branch: documentation
        build_dir: public/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
